### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by crisidev** [ansible/tacacs_plus#16]
I think what is missing now is a more structured documentation, especially as inline, with sphinx autogeneration and automatic push to readthedocs.

@ryanpetrello do you guys have an account on readthedocs? The sphinx generation part is quite easy to implement thou..

Regarding the inline documentation, here is the status:
```
tacacs_plus/flags.py - not documented
tacacs_plus/accounting.py - not documented
tacacs_plus/authentication.py - not documented
tacacs_plus/authorization.py - not documented
tacacs_plus/client.py - documented
tacacs_plus/flags.py - not documented
tacacs_plus/packet.py - not documented
```

Thoughts?

**Comment by ryanpetrello** [comment]
@crisidev no RTD account, but I'm comfortable enough w/ sphinx to set this up (if we actually had thorough docs, which we currently don't)

**Comment by crisidev** [comment]
I can set this up, no problem. You just have to create the RTD account. On my local machine I can already generate doc for what we have documented. It can be a work in progress and improved ongoing :)

**Comment by crisidev** [comment]
Implemented here: #18

**Comment by ryanpetrello** [comment]
http://tacacs-plus.readthedocs.io/en/latest/

**Comment by crisidev** [comment]
Nice :D Now the doc is to be written, which is tedious :D
