### ISSUE TITLE
Query - how to make this effect before user login so the authentication refers to TACACS server instead of local?

### ISSUE THREAD

**Issue by skchao** [ansible/tacacs_plus#42]
Hi, Not sure if this is the question related to your package or simply related to UNIX(ubuntu) administration? any advice is deeply appreciated

**Comment by skchao** [comment]
hi just to reiterate my question. In other tacacs client package I see it create the '/usr/local/lib/security/pam_tacplus.so' file and to be referred by /etc/pam.d/ so when user login to a server the login process can redirect the authentication to the server. Are you able to offer your module in the similar format? that will be deeply appreciated!

**Comment by crisidev** [comment]
Hello fellow AAA friend. This package is not meant to be a Tacacs+ PAM module as it will need a lot of work to be able to be integrated successfully with a C based environment like PAM.
