### ISSUE TITLE
License file is missing in pypi package

### ISSUE THREAD

**Issue by szymon-musiol** [ansible/tacacs_plus#43]
Pypi.org package for version 2.6 do not contain LICENSE file. Is it on purpose? If not then maybe it could be added.

https://pypi.org/project/tacacs_plus/

**Comment by ryanpetrello** [comment]
Nope, looks like an accident.

**Comment by crisidev** [comment]
I will soon release a new version, see #51 .. I'll close this and make sure we have the LICENCE file in the new release
